name: build

on:
  workflow_dispatch:
  push:
    paths:
    - "**.py"
    - "requirements.txt"
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Cover tests in non-Blender env
      run: |
        coverage run -m unittest -v
        mv .coverage .coverage.non-blender
    - name: Cover tests inside Blender env
      uses: docker://nytimes/blender:2.92-cpu-ubuntu18.04
      with:
        entrypoint: /bin/sh
        args: scripts/cover_bl_tests_in_blender.sh
    - name: Combine Coverage results
      run: |
        coverage combine
        coverage report
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2.1.0
