name: docs

on:
  push:
    tags:
    - "v[0-9].[0-9]+.[0-9]+"

  workflow_dispatch:
    inputs:
      tag:
        description: Tag (version)
        required: true

jobs:
  publish_docs:

    runs-on: ubuntu-latest
    
    steps:
    - name: Parse docs version
      id: docs-version
      uses: actions/github-script@v3
      with:
        result-encoding: string
        script: |
          const ref = context.ref
          console.log(`Evaluating ref='${ ref }'`)
          const tag = ref.startsWith("refs/tags")
            ? ref.substring(10) : context.payload.inputs.tag
          return tag
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: refs/tags/${{ steps.docs-version.outputs.result }}
        path: ./main
    - name: Set up Python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.9
    - name: Install dependencies
      working-directory: ./main
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build sphinx docs
      working-directory: ./main/docs
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sphinx-build -M html source build -D release=${{ steps.docs-version.outputs.result }}
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: ./publish
    - name: Publish docs
      working-directory: ./publish
      env:
        RELEASE: ${{ steps.docs-version.outputs.result }}
      run: |
        rm -rf ./$RELEASE
        cp -r ../main/docs/build/html ./$RELEASE
        echo "{" > versions.json
        find . -maxdepth 1 -mindepth 1 -type d -name "v?.?.?" | sort -r | while read dir; do
          echo "  \"${dir##*/}\": \"$dir/\"," >> versions.json
        done
        truncate -s -2 versions.json
        echo >> versions.json
        echo "}" >> versions.json
        git add .
        git config --local user.name "github-actions"
        git config --local user.email "actions@github.com"
        git commit -m "Publish docs $RELEASE"
    - name: Deploy to gh-pages
      working-directory: ./publish
      run: |
        if [ $ACT ]; then
          dry_run="-n"
        fi
        git push $dry_run
