name: Release

on:
  push:
    tags:
    - "v[0-9].[0-9]+.[0-9]+"

  workflow_dispatch:
    inputs:
      tag:
        description: Tag (version)
        required: true

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: get-tag
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const ref = context.ref
            console.log(`Evaluating ref='${ ref }'`)
            const tag = ref.startsWith("refs/tags")
              ? ref.substring(10) : context.payload.inputs.tag
            return tag
      - uses: actions/checkout@v3
        with:
          ref: refs/tags/${{ steps.get-tag.outputs.result }}
      - name: Build
        env:
          ADDON_SRC_DIR: blender_extra_tools
        run: |
          cp LICENSE $ADDON_SRC_DIR
          mkdir build
          zip -r build/addon_$ADDON_SRC_DIR.zip $ADDON_SRC_DIR
      - name: Create Release and upload assets
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALLOW_TAG_PREFIX: "true"
        with:
          args: build/*.zip
