name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: true
  push:
    tags:
    - "*"

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Set GITHUB_REF manually
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "GITHUB_REF='refs/tags/${{ github.event.inputs.tag }}'" >> $GITHUB_ENV
      - name: Checkout tag ${{ github.event.inputs.tag }}
        uses: actions/checkout@v2
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          ref: refs/tags/${{ github.event.inputs.tag }}
      - uses: actions/checkout@v2
        if: ${{ github.event_name != 'workflow_dispatch' }}
      - name: Build
        run: |
          cp LICENSE $ADDON_SRC_DIR
          mkdir build
          zip -r build/addon_$ADDON_SRC_DIR.zip $ADDON_SRC_DIR
        env:
          ADDON_SRC_DIR: "blender_extra_tools"
      - name: Create Release and upload assets
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF: refs/tags/${{ github.event.inputs.tag }}
          ALLOW_TAG_PREFIX: "true"
        with:
          args: build/*.zip
